### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by gregsdennis** [jsonsystems/public#10]
Please add text to the site and readme to dissociate this site from my .Net library, [JsonSchema.Net](https://www.nuget.org/packages/JsonSchema.Net/).

There's a playground for my library at https://json-everything.net/json-schema.

**Comment by jackwootton** [comment]
Hi Greg, thanks for posting this issue. In order to keep the site clean I would rather not add notices about other projects. I receive many such requests and satisfying all of them would negatively impact the UX of the site.  For a similar reason, trying to add a potentially long list of projects which www.jsonschema.net is **not**, would likely result in outdated documentation pretty quickly. I do want to avoid confusion though. Perhaps there is a way you could add some clarifications to your project to help reduce any confusion?
